# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
        migrations.AlterModelTable(
            name='transport',
            table='transport',
        ),
    ]
