# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allorder', '0004_orders_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_money',
        ),
    ]
