# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allorder', '0005_remove_orders_order_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='fact_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='实际支付'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='商品总价'),
        ),
    ]
