# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allorder', '0006_auto_20181130_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=200, verbose_name='订单地址'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='allorder.Payment', verbose_name='付款方式'),
        ),
    ]
