# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allorder', '0008_auto_20181130_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allorder.Payment', verbose_name='付款方式'),
        ),
    ]
