# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181118_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
