# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('pic', models.ImageField(default='images/s1.png', upload_to='goods/%Y%m', verbose_name='图片')),
                ('url', models.CharField(default='', max_length=200, verbose_name='url地址')),
            ],
            options={
                'verbose_name': '首页活动表',
                'verbose_name_plural': '首页活动表',
                'db_table': 'active',
            },
        ),
        migrations.CreateModel(
            name='AreaGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('script', models.CharField(max_length=200, verbose_name='描述')),
                ('order', models.IntegerField(verbose_name='排序')),
            ],
            options={
                'verbose_name': '特色专区表',
                'verbose_name_plural': '特色专区表',
                'db_table': 'areaGoods',
            },
        ),
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='分类名')),
                ('introduce', models.CharField(max_length=200, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '商品分类表',
                'verbose_name_plural': '商品分类表',
                'db_table': 'assortment',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(default='', max_length=30, verbose_name='买家名')),
                ('content', models.CharField(default='', max_length=200, null=True, verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('detail', models.CharField(max_length=200, verbose_name='商品详情')),
            ],
            options={
                'verbose_name': '商品spu表',
                'verbose_name_plural': '商品spu表',
                'db_table': 'good',
            },
        ),
        migrations.CreateModel(
            name='GoodPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('pic_url', models.CharField(max_length=200, verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '商品相册表',
                'verbose_name_plural': '商品相册表',
                'db_table': 'goods_pic',
            },
        ),
        migrations.CreateModel(
            name='Goodsku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('introduce', models.CharField(default='', max_length=200, verbose_name='商品简介')),
                ('unit', models.IntegerField(choices=[(1, '件'), (2, '斤'), (3, '箱')], default=1, verbose_name='单位')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('url', models.CharField(default='', max_length=100, verbose_name='商品图片地址')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sale_num', models.IntegerField(default=0, verbose_name='销量')),
                ('logo_url', models.CharField(default='', max_length=100, verbose_name='logo地址')),
                ('isGround', models.BooleanField(default=True, verbose_name='是否上架')),
                ('assortment_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='goods.Assortment', verbose_name='商品分类id')),
                ('good_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='goods.Good', verbose_name='商品spu表id')),
            ],
            options={
                'verbose_name': '商品sku表',
                'verbose_name_plural': '商品sku表',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='LunBo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='轮播名称')),
                ('pic_url', models.CharField(max_length=100, verbose_name='图片地址')),
                ('order', models.IntegerField(verbose_name='排序')),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goodsku', verbose_name='商品sku')),
            ],
            options={
                'verbose_name': '轮播表',
                'verbose_name_plural': '轮播表',
                'db_table': 'lunbo',
            },
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.AreaGoods', verbose_name='特色专区id')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goodsku', verbose_name='商品sku表id')),
            ],
            options={
                'verbose_name': '专区商品表',
                'verbose_name_plural': '专区商品表',
                'db_table': 'produce',
            },
        ),
        migrations.AddField(
            model_name='goodpic',
            name='good_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goodsku', verbose_name='商品id'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goodsku', verbose_name='上级'),
        ),
    ]
