# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181123_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='areagoods',
            name='is_sale',
            field=models.BooleanField(default=1, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='goodpic',
            name='pic_url',
            field=models.ImageField(upload_to='goods/pic', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='goodsku',
            name='logo_url',
            field=models.ImageField(default='', upload_to='goods/%Y%m', verbose_name='logo地址'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='pic_url',
            field=models.ImageField(upload_to='goods/banner', verbose_name='图片地址'),
        ),
    ]
