# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 16:08
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181124_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品详情'),
        ),
    ]
