# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181124_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortment',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
