# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_assortment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsku',
            name='unit',
            field=models.IntegerField(choices=[(1, '件'), (2, '斤'), (3, '箱')], verbose_name='单位'),
        ),
    ]
