# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('username', models.CharField(max_length=100, verbose_name='收货人')),
                ('phone', models.CharField(max_length=11, verbose_name='收货人电话')),
                ('proper', models.CharField(blank=True, default='', max_length=100, verbose_name='省')),
                ('city', models.CharField(max_length=100, verbose_name='市')),
                ('area', models.CharField(blank=True, default='', max_length=100, verbose_name='区')),
                ('brief', models.CharField(max_length=255, verbose_name='详细地址')),
                ('isDefault', models.BooleanField(default=False, verbose_name='是否设置为默认')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '收货地址表',
                'verbose_name_plural': '收货地址表',
            },
        ),
    ]
