# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='infor',
            name='birthday',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='infor',
            name='hometown',
            field=models.CharField(max_length=100, null=True, verbose_name='故乡'),
        ),
        migrations.AlterField(
            model_name='infor',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='infor',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='infor',
            name='school',
            field=models.CharField(max_length=100, null=True, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='infor',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
    ]
