# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infor',
            options={'verbose_name': '个人资料表', 'verbose_name_plural': '个人资料表'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '账号表', 'verbose_name_plural': '账号表'},
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='useraddress',
        ),
    ]
