# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181120_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='head',
            field=models.ImageField(default='images/infortx.png', upload_to='static/media/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='infor',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='infor',
            name='hometown',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='故乡'),
        ),
        migrations.AlterField(
            model_name='infor',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='infor',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='infor',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学校'),
        ),
    ]
