# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181125_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='area',
            new_name='harea',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='proper',
            new_name='hcity',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='city',
            new_name='hproper',
        ),
    ]
